name: Natural Number Test

on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Natural eded yoxlamasi
        run: |
          # Burada yeni fayli yoxlayiriq
          for n in $(cat test_ededler.txt); do
            if [[ ! "$n" =~ ^[0-9]+$ ]] || [ "$n" -eq 0 ]; then
              echo "XETA: '$n' natural deyil!"
              exit 1
            fi
          done
          echo "Test ugurlu oldu."

      - name: Tek ve Cut ayirma
        run: |
          echo "Tekler:"
          awk '$1 % 2 != 0' test_ededler.txt
          echo "Cutler:"
          awk '$1 % 2 == 0' test_ededler.txt
